
export const ActionTypes = {
    SET_STUDENTS: "SET_STUDENTS",
    SET_BOOKS: "SET_BOOKS",
    SET_TRANSACTIONS: "SET_TRANSACTIONS",
    
    SELECTED_STUDENT: "SELECTED_STUDENT",
    SELECTED_BOOK: "SELECTED_BOOK",
    SELECTED_TRANSACTION: "SELECTED_TRANSACTION"
}
